title: Tech Spice
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ":title/"
baseurl: "/techspice" # the subpath of your site, e.g. /blog
url: "https://cherisea.github.io/techspice" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Joey Cherisea # add your name
author-img: joey_cherisea.jpg
about-author: Present the tech world to you with a sense of humor and light touch that pique your interest, ignite your passion and lead you to a journey of self-fullfilment.
social-twitter: # add twitter handle
social-facebook: # add your Facebook handle
social-github: Cherisea
social-linkedin: joey-cherisea
social-email: joeycherisea@gmail.com

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
